db:
  host: "localhost"
  port: "5432"
  user: "postgres"
  password: "password"
  name: "go_microservices"
user-microservice:
  host: "user-microservice"
  port: "3003"
auth-microservice:
  host: "auth-microservice"
  port: "3001"
article-microservice:
  host: "article-microservice"
  port: "3002"
jwt:
  secret: "MIIBOgIBAAJBAK/Zm/tfO1YPEVr61O+DrJuyrUXOGUXDqNaHwPvaHQUIY8fB8oB+"