---
apiVersion: v1
kind: Service
metadata:
  name: article-microservice
spec:
  type: NodePort
  ports:
  - name: http
    port: 3002
    targetPort: 3002
    nodePort: 30002
  selector:
    app: article