---
apiVersion: v1
kind: Service
metadata:
  name: auth-microservice
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: '/metrics'
    prometheus.io/port: "3101"
spec:
  type: NodePort
  ports:
  - name: http
    port: 3001
    targetPort: 3001
    nodePort: 30001
  - name: monitoring
    port: 3101
    targetPort: 3101
    nodePort: 30101
  selector:
    app: auth