---
apiVersion: v1
kind: Service
metadata:
  name: gateway-microservice
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "3000"
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    app: gateway