---
apiVersion: v1
kind: Service
metadata:
  name: gateway-microservice
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    targetPort: 3000
    nodePort: 30000
  selector:
    app: gateway